### ISSUE TITLE
Ignore savings plan/reserved instance costs in allocation showback

### ISSUE THREAD

**Issue by kirbsauce** [opencost/opencost#1018]
Filing on behalf of a customer:  The ask to be able to include the savings plan costs in some queries (higher-level reporting) and remove them from the lower-level/showback information since the savings plan costs are out of the control of the showback recipients.

**Comment by AjayTripathy** [comment]
Just a note, the ability to apply/remove/configure savings plan / RI information has been brought up a few times. It's definitely something worth considering.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
