### ISSUE TITLE
Custom charts for overview page

### ISSUE THREAD

**Issue by pinlast** [opencost/opencost#1027]
Looks like on the overview page I have access only to pre-defined charts, but we would like to add  `Product Allocation` chart next to the existing `Controller Allocation` and `Service Allocation`. Is there any way to add custom charts on the overview page?

gz#1222

**Comment by AjayTripathy** [comment]
Hi @pinlast that's not possible today but sounds like a great feature request!

**Comment by dwbrown2** [comment]
@pinlast I'd like Kubecost to offer more flexibility here. We're slammed on other projects now but would love to see if we can offer something in the future. 

It's not a perfect substitute but we do see teams doing lots of customization with our Prometheus metrics in Grafana dashboard. Just wanted to see in case you wanted to explore right away.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
