### ISSUE TITLE
Allow simulator to be configured to match autoscaler

### ISSUE THREAD

**Issue by kirbsauce** [opencost/opencost#1029]
Improve savings recommendations accuracy by allowing the simulator to be configured to better match the user's autoscaler.

**Comment by michaelmdresser** [comment]
Which savings recommendations? Cluster node right-sizing?

Which autoscaler parameters should we look into?

**Comment by AjayTripathy** [comment]
http://demo.kubecost.io/action.html?a=unusednodes this is the cluster-autoscaler simulator

**Comment by prakharporwal** [comment]
Can I contribute to this repo. is it open for public contributions ?

**Comment by AjayTripathy** [comment]
Hi @prakharporwal the cluster autoscaler simulator is not yet open source, but we're exploring options here and can circle back!

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
