### ISSUE TITLE
Aggregate by Cloud provider account/project

### ISSUE THREAD

**Issue by ivankube** [opencost/opencost#1150]
Add aggregation by cloud provider account.

Kubecost needs to understand which Cloud Provier account/project a resource is part of and to make that part of the metadata; the resource can be a k8s pod/deployments or a CUR item.

gz#1626<br><br>

**Comment by dwbrown2** [comment]
Thanks for reporting. 

Do we already support what is needed on the assets side and just need this in allocation? Or there is more of a need? Any specific use case that has been shared from users?

**Comment by kirbsauce** [comment]
@dwbrown2 , ZD 1626 (noted above) has more information if that helps, but here's the original...

"Good morning -- we've rolled out KubeCost internally to an early set of users! An early question came back whether we can aggregate by AWS account. Specifically, they want to aggregate by their deployment (via a k8s label) and then by AWS account. Today you can aggregate by Cluster -- is there a feature request to also allow Account aggregation by default?"

**Comment by dwbrown2** [comment]
@AjayTripathy this seems very straightforward if we already have Account in Allocation ETL. Do you know if that's the case? 

If we don't want to bring it to ETL for some reason, then this is potentially an Advanced Reporting use case.

**Comment by AjayTripathy** [comment]
It does not exist in the allocation API today. It feels like an advanced reporting usecase since this is joining cloud provider concepts with kubernetes concepts. We are actively trying to remove the dependencies of k8s data from cloud provider data.

**Comment by Adam-Stack-PM** [comment]
@teevans @wolfeaustin  Based on Ajay's last note wanted to get this on your radar for advanced reports.

**Comment by dwbrown2** [comment]
I could be misguided, but I feel like the backend should handle this is some capacity and not push to FE reporting... e.g. when you add a cloud provider integration we should know what provider, account, project that cluster is in.

**Comment by AjayTripathy** [comment]
So I think the core question we're trying to answer here is: What are all the pods (or other k8s aggregations) in a particular AWS account? 

You can already script an answer to this question out of our APIs; on Assets API, filter nodes by accountID, then take all those nodes and plug them in as filters to the Allocations API. This feels like manipulation of two separate concerns (Cloud data and K8s data) and is a join of the data. I'm agnostic about whether this sort of query is better joined in the frontend or on the backend, but I do want to avoid doing this by denormalizing the data and tagging every container with its account, since that comes at a large additional memory cost.

**Comment by teevans** [comment]
So this makes sense - The only question I would ask is what is the cost of executing these queries on the front end in terms of response time, vs us building this query into the BE?

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
