### ISSUE TITLE
ETL misconfiguration can cause millions of logs

### ISSUE THREAD

**Issue by dramich** [opencost/opencost#1171]
This is a new issue based off the discussion https://github.com/kubecost/cost-model/issues/1122#issuecomment-1102790936
```
E0330 16:41:39.748529       1 log.go:17] [Error] ETL: Allocation: automatic reconciliation: error reconciling range for [2022-03-30T15:00:00+0000, 2022-03-30T16:00:00+0000): error querying for AllocationSetRange to reconcile: boundary error: requested [2022-03-30T15:00:00+0000, 2022-03-30T16:00:00+0000); supported [2022-03-28T15:00:00+0000, 2022-03-30T14:25:43+0000): ETL: Allocation[1h] is 100.0% complete
I0330 16:41:39.748535       1 log.go:47] [Info] ETL: Allocation: automatically reconciling [2022-03-30T15:00:00+0000, 2022-03-30T16:00:00+0000) (0.00% complete)
I0330 16:41:39.748545       1 log.go:47] [Info] ETL: Asset[1h]: Query [2022-03-30T15:00:00Z, 2022-03-30T16:00:00Z)
```

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).

**Comment by pierluigilenoci** [comment]
OpenCost's (formerly KubeCost) approach to handling open tickets never disappoints (I'm ironic).
