### ISSUE TITLE
AWS ALB cross-zone traffic should be classified as in-zone

### ISSUE THREAD

**Issue by SapientGuardian** [opencost/opencost#1183]
Per https://aws.amazon.com/elasticloadbalancing/faqs/ 
>Since cross-zone load balancing is always on with Application Load Balancer, you are not charged for this type of regional data transfer.

I have my VPC subnets configured under `direct-classification` to ensure that traffic outside of the cluster is properly tagged. This works as advertised, but cross-zone ALB traffic is an exception and should be charged as in-zone. The incorrect classification of this traffic for high-bandwidth services inflates their cost by thousands of dollars per day.

I don't have a good solution to propose for this. Specifically, I'm not sure how to differentiate ALB traffic from regular EC2 traffic given only an ip address. You _can_ harvest all internal IPs of ALBs by querying all ENIs in the account and filtering by descriptions that start with "ELB", but that's rather inelegant and might include NLBs for which the exception is not valid. 

Even if I was willing to find all internal ELB IPs by hand, `direct-classification` overrides `destinations.in-zone` (which seems like it should be the reverse to me, but it is what it is), so I don't have a way of supplying that information. I'm not sure how often those IPs change, so that might be a game of cat and mouse anyway.

If there was some way to completely ignore network costs for a specific namespace or label I could at least stop these particularly high-bandwidth services from throwing off my cost estimates, but without that I'm forced to turn off network cost allocation entirely.

gz#1742<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1742'>Zendesk ticket #1742</a>)</i>

**Comment by keithhand** [comment]
Hello @SapientGuardian, thank you for submitting this! I will tag our product team to get some more eyes on this request.

**Comment by dwbrown2** [comment]
Thanks for the report, @SapientGuardian! @mbolt35 would love to get your input here while I review this week.

One thing to point out is that AWS cost reconciliation would account for this and revise estimates downwards as soon as your bill is available. Are you seeing this behavior @SapientGuardian?

**Comment by SapientGuardian** [comment]
I'm in an unusual situation in which I actually _want_ estimates based on retail prices rather than what's in our AWS bill. To that end, I have not hooked up kube-cost to our cost and usage report.

Without going into too many details, the company I work for has us budget to the _retail_ cost of AWS services even though we have discounted pricing and things like reserved instances. We also have our own in-house tool which applies those rules and allocates the line-items from our AWS bill to various teams by the tags applied to AWS resources (but again, it pretends like we pay retail). This leaves us with one large "kubernetes" line item that requires further explanation. Kube-cost is great at breaking down the compute cost, but networking costs are a challenge because of this particular issue.

**Comment by mbolt35** [comment]
@SapientGuardian Thanks for the report. Because the network-costs pods do not use any provider specific code, it's not currently an option for the implementation to hook in the ALB IPs, but it does seem feasible to create a config that uses direct classification for LBs queried manually. The AWS docs provide details how to locate the ALB IPs:

```
aws ec2 describe-network-interfaces --filters Name=description,Values="ELB elb-name" --query 'NetworkInterfaces[*].PrivateIpAddresses[*].PrivateIpAddress' --output text
```
Replace **elb-name** with one of the following:

* For Classic Load Balancers: Name of the load balancer
* For Application Load Balancers: app/load-balancer-name/load-balancer-id
* For Network Load Balancers: net/load-balancer-name/load-balancer-id
* For Application Load Balancers and Network Load Balancers, use the following command to find the load-balancer-id:
```
aws elbv2 describe-load-balancers --names load-balancer-name
```

The load-balancer-id is the last field of characters that follows the trailing slash after the load balancer's name in the ARN.

This excerpt was pulled from https://aws.amazon.com/premiumsupport/knowledge-center/elb-find-load-balancer-IP/

It does sound as if there is some conflict between the classifications that you're running into. Can you provide a bit more detail there? 

The direct classification was designed to override the automated classification, so it will always be priority.

**Comment by SapientGuardian** [comment]
Within our VPC we have multiple subnets, spread across availability zones (for simplicity, let's say we have one subnet in us-west-2a and one subnet in us-west-2b). 

* Kubernetes nodes exist in both subnets, and the classification of traffic between services on these nodes happens automatically because the nodes are labeled/annotated .
* We have services outside of Kubernetes which also exist in these subnets, so in order to correctly classify this traffic I have our subnets provided explicitly in `direct-classification`.
* The internal IP addresses for the ALB also exist within these subnets. Those ip addresses get classified as being `in-zone` when that is the case and `cross-zone` when they're not, From a strict networking perspective, ALB traffic gets classified correctly. The problem is that for billing purposes, cross-zone ALB traffic should be treated as `in-zone`.

If I use the CLI commands you mentioned and extract all of the ALB IPs (assuming for the moment that the resulting list is stable) I would need to put them in the `in-zone` configuration for them to be factored into the cost estimate correctly. But even if I did that, it would still get overridden by the subnets specified in `direct-classification` and charged as `cross-zone`.

**Comment by mbolt35** [comment]
> The internal IP addresses for the ALB also exist within these subnets. Those ip addresses get classified as being in-zone when that is the case and cross-zone when they're not, From a strict networking perspective, ALB traffic gets classified correctly. The problem is that for billing purposes, cross-zone ALB traffic should be treated as in-zone.

Thanks for providing the details here, this all make sense. Going to discuss this with the team and see what we can come up with. 

>  I use the CLI commands you mentioned and extract all of the ALB IPs (assuming for the moment that the resulting list is stable)

I know this approach is not optimal, and I do think it's possible for an ALB to update its internal IP (based on the same docs I linked). We're currently investigating live configmap updates for network-costs, and while this doesn't fully resolve the problem, perhaps it gives you more flexibility (granted we can solve the config overlap issue)?

**Comment by SapientGuardian** [comment]
Yes, I could certainly rig up a cron job to periodically get the latest set of ALB IPs and put them in a configmap.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
