### ISSUE TITLE
CUR integration shows green check mark despite integration not being set

### ISSUE THREAD

**Issue by AjayTripathy** [opencost/opencost#1190]
see https://github.com/kubecost/cost-model/issues/1145#issuecomment-1092487546

The correct behavior is to clearly show the CUR as unintegrated when it's not set up-- cc @gkaskonas

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
