### ISSUE TITLE
Exclude nodes

### ISSUE THREAD

**Issue by aslafy-z** [opencost/opencost#1204]
I have some nodes that are underutilized "by-design", these are labeled specifically. Is there a way I could exclude them from the kubecost UI / reports?

gz#1802<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1802'>Zendesk ticket #1802</a>)</i>

**Comment by kirbsauce** [comment]
Hi @aslafy-z , thanks for the enhancement request!  We have something similar here-> https://github.com/kubecost/cost-analyzer-helm-chart/issues/1017 which could probably be broadened to include nodes and other k8s objects.

**Comment by dwbrown2** [comment]
@aslafy-z thanks for sending! can you share more about your situation/goals and what reports you're looking to exclude these assets from?

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
