### ISSUE TITLE
Outlier detection appears to be causing pricing inaccuracy 

### ISSUE THREAD

**Issue by kbrwn** [opencost/opencost#1215]
Instance type = SPOT ec2 m5.16xlarge
AWS  = 15.70675
Kubecost = 0.158

Kubecost API:

```
{'name': '<redacted>', 'start': '2022-05-08T00:00:00Z', 'end': '2022-05-09T00:00:00Z', 'cpuCoreRequestAverage': 8.556347222222223, 'cpuCoreUsageAverage': 0.8579305287911569, 'cpuCost': 0.10444799999999993, 'gpuCost': 0, 'networkCost': 0, 'loadBalancerCost': 0.03599500069434801, 'pvCost': 0.608219178082192, 'ramByteRequestAverage': 23883779640.88889, 'ramByteUsageAverage': 5065592058.3111105, 'ramCost': 0.05345532641601566, 'sharedCost': 0, 'externalCost': 0}```
```

Logs repeated in bug report: 

```
 [Warning] CPU cost outlier detected; skipping data point.
 [Warning] RAM cost outlier detected; skipping data point.
```

Codeblock: https://github.com/kubecost/cost-model/blob/v1.93.1/pkg/costmodel/metrics.go#L532-L549

@nealormsbee Mentioned this logic was perhaps related and maybe should be removed.

**Comment by AjayTripathy** [comment]
Can we get a little more information (maybe in the logs, maybe asking the user) about the magnitude of the data point before making a final decision here?

**Comment by Adam-Stack-PM** [comment]
@srpomeroy After you merge #1251 could we make sure it addresses this issue?  Thanks for connecting the PR.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
