### ISSUE TITLE
ask build question

### ISSUE THREAD

**Issue by mark6969** [opencost/opencost#1231]
Hi i want ask some question 
when i try build kubecost with this code 
![圖片](https://user-images.githubusercontent.com/36353259/171523714-63a43135-2276-4465-80fb-44bdbe55debc.png)
will show this error
![圖片](https://user-images.githubusercontent.com/36353259/171524058-42c34faa-dac4-4cf2-b40a-57d61cc70a49.png)
if i change my code like this
![圖片](https://user-images.githubusercontent.com/36353259/171524313-5bd70194-cab4-41ee-8332-118bd304ee22.png)
i can build 
![圖片](https://user-images.githubusercontent.com/36353259/171524378-15c311bd-d5a4-41ef-a4fb-9784efec9ce4.png)
but some pods always in Pending
![圖片](https://user-images.githubusercontent.com/36353259/171524561-5283e355-0600-4f79-9aba-4a5ed7dd1058.png)
i use `kubectl describe`
![圖片](https://user-images.githubusercontent.com/36353259/171524957-e8cea653-8422-4414-b4ee-5a7bbd7e63a9.png)
if need any else please tell me, thank

gz#1908<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1908'>Zendesk ticket #1908</a>)</i>

**Comment by ivankube** [comment]
You can either remove podSecurityPolicy or use podSecurityPolicy=false when running helm install.

**Comment by AjayTripathy** [comment]
Hi @mark6969 it actually looks like the pod is pending because of this:
```
0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaim"
```

It's likely the backing persistent volume didn't get properly provisioned. Do you automatically provision volumes based on persistent volume claims? If not you'll need to manually provision one. Here's a general article that can help support. https://stackoverflow.com/questions/52668938/pod-has-unbound-persistentvolumeclaims

**Comment by mark6969** [comment]
i will try your suggestions thanks

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
