### ISSUE TITLE
GCP Spot instances are not recognized

### ISSUE THREAD

**Issue by kamilkrampa** [opencost/opencost#1278]
GCP Spot VM is successor of Preemptible VMs: https://cloud.google.com/compute/docs/instances/spot. Spot instances have a different label: `cloud.google.com/gke-spot`.  Currently, for spot c2-standard-16 kubecost shows the following values
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/93582867/175506845-b427f14e-093d-4102-af34-585f27c5a956.png">

As you can see, discount is included, which shouldn't be the case for spot instance, and also the price is wrong as spot c2-standard-16 costs $0.2021/h. Preemptible and Spot have the same pricing.

gz#2035<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2035'>Zendesk ticket #2035</a>)</i>

**Comment by kamilkrampa** [comment]
Proposed fix: https://github.com/kubecost/opencost/pull/1279

**Comment by dwbrown2** [comment]
Thanks for this contribution, @kamilkrampa! A lot of our team is at Open Source Summit but we'll get this reviewed soon for you.

**Comment by Adam-Stack-PM** [comment]
@kamilkrampa Great work. Thanks for your contribution

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
