### ISSUE TITLE
Make `minsPerResolution` configurable in cluster.go

### ISSUE THREAD

**Issue by jcharcalla** [opencost/opencost#1291]
We should be reading `minsPerResolution` out of the `kubecostModel.etlResolutionSeconds` parameter instead of hardcoding the value. 

Here is the environment variable link.
https://github.com/kubecost/opencost/blob/e5dc00d4fb594f1f4b6dfc098414e09f6eec599f/pkg/env/costmodelenv.go#L68

And here is where it is hardcoded to 1 min.
https://github.com/kubecost/opencost/blob/6ddb2d8c4766a72c7303443487dcaa1be494b3f7/pkg/costmodel/cluster.go#L391

**Comment by Adam-Stack-PM** [comment]
@teevans Looks like an open issue from last weeks support rotation. Could you assign a priority P0,1,2 and remove the needs triage label?

**Comment by teevans** [comment]
@jcharcalla - What do you think is a good priority level for this?

**Comment by AjayTripathy** [comment]
I think that this should be done before the release, it's a clear bug and a very small fix

**Comment by Adam-Stack-PM** [comment]
@avrodrigues5, How is this item going?  Anything blocking getting a PR opened today?

**Comment by avrodrigues5** [comment]
@Adam-Stack-PM , I will sort out some help for testing and open a PR by EOD. 

Just one question, issue mentions only one occurrence of minsPerResolution but there are 4 and 3 occurrence hardcoded to 1 (line No 139, 391, 547) while one occurrence (line No 673) hardcoded to 5 in file https://github.com/kubecost/opencost/blob/6ddb2d8c4766a72c7303443487dcaa1be494b3f7/pkg/costmodel/cluster.go#L391 . What should be the default value 1 or 5?

**Comment by Adam-Stack-PM** [comment]
@avrodrigues5 Thanks for getting this out. Where you able to get answers to your questions?

**Comment by avrodrigues5** [comment]
@Adam-Stack-PM 
More i looked at this issue more questions i had
1. So the function that's used to compute [ETLResolution](https://github.com/kubecost/opencost/blob/08a98fac21673210f8b52681395e89188b08b7a1/pkg/env/costmodelenv.go#L451-L461) seems to default to 1m for prometheus user and if thanos is enabled only computes it to anything other than 1m default to 5m. Also what happens if user passes less than 60 seconds or between 60-120 seconds should it round down or round up, because it is a possibility.
2. Original question wasnt answered if i need to change all the hardcoded reference or just one but i went ahead and changed all of them. 

This Pr is minimalistic change but will wait for reviewers to see what they think.

**Comment by teevans** [comment]
cc @michaelmdresser

**Comment by Adam-Stack-PM** [comment]
Let's hold this PR until to v1.96. @michaelmdresser, had some great points around the importance of testing in this area.

**Comment by Adam-Stack-PM** [comment]
@AjayTripath. Based on our conversations with Michael pulling this out of the release to give more time for testing.  If we patch will try to get it in.  CC @avrodrigues5

**Comment by avrodrigues5** [comment]
The corresponding PR changes are in Develop Branch. Closing this Issue
