### ISSUE TITLE
ui: add `crossorigin="use-credentials"` for link rel="manifest"

### ISSUE THREAD

**Issue by fedordikarev** [opencost/opencost#1333]
We use `oauth2-proxy` to authorise access to admin tools and that breaks loading `manifest.json`
I checked that adding `crossorigin="use-credentials"` fixes that problem, but I did it using `sub_filter` in nginx configuration which is not good solution I think.

Should it be added by default to the index.html?

**Comment by AjayTripathy** [comment]
Hey @fedordikarev I'm supportive here. Maybe you could open a PR either with your solution or the proposed solution for review?

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
