### ISSUE TITLE
CVE-2022-21698 in dependency github.com/prometheus/client_golang v1.0.0

### ISSUE THREAD

**Issue by peijianju-sonrai** [opencost/opencost#1338]
Dear Opencost team

github.com/prometheus/client_golang v1.0.0 is having High CVE CVE-2022-21698

Any patch to address it? thank you

```
===================================
Total: 1 (HIGH: 1, CRITICAL: 0)

+-------------------------------------+------------------+----------+-------------------+---------------+---------------------------------------+
|               LIBRARY               | VULNERABILITY ID | SEVERITY | INSTALLED VERSION | FIXED VERSION |                 TITLE                 |
+-------------------------------------+------------------+----------+-------------------+---------------+---------------------------------------+
| github.com/prometheus/client_golang | CVE-2022-21698   | HIGH     | v1.0.0            | 1.11.1        | prometheus/client_golang:             |
|                                     |                  |          |                   |               | Denial of service using               |
|                                     |                  |          |                   |               | InstrumentHandlerCounter              |
|                                     |                  |          |                   |               | -->avd.aquasec.com/nvd/cve-2022-21698 |
+-------------------------------------+------------------+----------+-------------------+---------------+---------------------------------------+


```

Regards,
Eric

**Comment by AjayTripathy** [comment]
Hi @peijianju-sonrai thanks for this report. We'll get this patch tested and upgraded soon.

**Comment by nickcurie** [comment]
In between 1.0.0 and 1.11.1 the API changed, so I need to go through and fix all the affected files. I've updated the package to 1.12.2 since the API is changed equally.

**Comment by nickcurie** [comment]
cc: @Adam-Stack-PM this is going to take a day or 2

**Comment by AjayTripathy** [comment]
Let's begin work on this but I don't think we should hold v1.96.0 release.

**Comment by AjayTripathy** [comment]
Especially since:
`
In order to be affected, an instrumented software must use any of promhttp.InstrumentHandler* middleware except RequestsInFlight; not filter any specific methods (e.g GET) before middleware; pass metric with method label name to our middleware; and not have any firewall/LB/proxy that filters away requests with unknown method. client_golang version 1.11.1 contains a patch for this issue. Several workarounds are available, including removing the method label name from counter/gauge used in the InstrumentHandler; turning off affected promhttp handlers; adding custom middleware before promhttp handler that will sanitize the request method given by Go http.Request; and using a reverse proxy or web application firewall, configured to only allow a limited set of methods.
`
We don't allow arbitrary methods to be used with prometheus. Sanitization happens within the application-- the set of http methods we use is limited.

**Comment by Adam-Stack-PM** [comment]
@AjayTripathy & @nickcurie, Thanks for the context and update here. What I'm hearing is if it gets done in time and we are confident in the testing, we will put it in v1.96.  If not, we will wait for v1.97 or v1.96.01. Let me know if this is not correct.
