### ISSUE TITLE
Asset PV Ingest window not populating

### ISSUE THREAD

**Issue by Sean-Holcomb** [opencost/opencost#1365]
Issue presents itself as spammy logs like these:
```
2022-07-27T21:10:35.429517321Z WRN Asset ETL: disk '<PV-NAME>' start outside window: 0001-01-01T00:00:00 not in [2022-07-27T01:00:00, 2022-07-27T02:00:00]
```
When these warnings occur the start and end of the disk are set to the start and end of the hourly or daily window being generated. This could cause an over estimation on cost in the windows where the Disk did not run for the whole hour. I have also seen these logs come up on tickets so I would be good to get rid of them as they can act as a red herring. 
The issue seems to lie here https://github.com/opencost/opencost/blob/cee0b6ee6df92fe2e1b23a48c5e6f52852fac7a5/pkg/costmodel/cluster.go#L1164-L1165
where the time is defaulted to 0, this happens because the asset PV query was changed so that this attempt to access the timestamp fails and the default is returned.

gz#2471<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2471'>Zendesk ticket #2471</a>)</i>

**Comment by AjayTripathy** [comment]
Good find! Cleaning these logs and making sure we get this right feels important to me. @Adam-Stack-PM I'd argue this is p1 and see if we can't knock it out in our next set of cleanups.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
