### ISSUE TITLE
Community feedback on idle definitions

### ISSUE THREAD

**Issue by dwbrown2** [opencost/opencost#1379]
When sharing OpenCost definitions at FinOps X and Open Source Summit, we received a number of insightful comments on the [current OpenCost idle definition](https://github.com/opencost/opencost/blob/develop/spec/opencost-specv01.md#idle-costs).

Specifically, multiple end users felt that the idle cost definition was incomplete. The viewed `total idle` as the combination between `cluster idle` and `workload idle`. I believe the OpenCost definition/section closely matches this feedback, but that fully adopting would be an improvement!

**Comment by nikovacevic** [comment]
I disagree with this feedback, personally, but happy to discuss. Were these commenters at all satisfied by the argument that the idea of "workload idle" is captured by "efficiency"? Can we call it "workload efficiency" to satisfy that? I think "idle" needs to remain "assets that have not been allocated" -- and we should not change the definition of "allocated."

**Comment by nikovacevic** [comment]
Though I have to agree -- that section on idle is not easy to comprehend. Happy to help draft changes there.

**Comment by nikovacevic** [comment]
What does this mean?
> Idle Costs can be calculated at both the Asset/Resource level as well as the Workload level.

**Comment by nikovacevic** [comment]
Seems to me that we want to communicate this better:
```
Idle Cost = (Total Kubernetes Compute Resource Cost) - (Allocated Kubernetes Compute Resource Cost)
Total KCRC = sum( cost of nodes )
Allocated KCRC = sum( cost of workloads on nodes, measured by max(resource, usage) per-resource )
```
The graphic is difficult to understand, and the terms and use of those terms are either (1) very unclear, or (2) simply incorrect.

**Comment by dwbrown2** [comment]
Helpful feedback, @nikovacevic! Sounds like there is disagreement with the recommendation of this formula?

```
total idle = cluster idle + workload idle
``` 

where 

```
cluster idle = unallocated capacity
workload idle = allocated but unused capacity
```

Any specific part of that you disagree with?

**Comment by dsterz** [comment]
Hi @nikovacevic,

I was involved in the initial discussions around the whole spec and also struggled with the idle cost chapter in particular and agree that it's not easy to comprehend and happy to support on drafting different versions that the community will like more.

I feel that discussing that in here is not the most efficient way so i propose to not have this github issue idle too much so let's allocate some time and concentrate our capacity ;) 

Let's plan a first session to draft some alternatives (that should become a PR), what do you think?

**Comment by nikovacevic** [comment]
> Sounds like there is disagreement with the recommendation of this formula?

@dwbrown2 yes, I have some disagreement there, but I understand the idea it's trying to communicate. The two issues are:

1. This formulation conflates two different ideas (i.e. cluster compute idle cost, workload efficiency) and puts them behind the single word "idle" -- but maybe we will decide that's intended.
2. The writing and graphics do not clearly communicate the existing idea (i.e. the conflated idle concept).

To try to tease these apart, here are some questions:
* Are we convinced that we want the unadorned name "idle" to refer to the difference between (cluster compute total cost) and (workload usage cost)?
* If so, do we need another word for "cluster idle" i.e. the difference between (total cluster compute asset cost) and (workload allocation cost)? Maybe we should call that "compute headroom" instead, or something?
* Do we dislike the term "efficiency" for the ratio of (workload usage cost) to (workload allocation cost)? Do we want a name for the difference between them? Currently that would be "workload idle" which is a fine name, if we're not using "idle" for a different idea.

**Comment by nikovacevic** [comment]
@dsterz I'd be happy to find some time to draft an alternative that could become a PR. We could either meet in early November, or we can collaborate asynchronously in a Google Doc -- do you have a preference?

**Comment by mfornasa** [comment]
Thanks everyone for the commentary above. I find that having a standardised spec is the way to go create a common vocabulary for the community to discuss k8s cost.

I agree that the Idle section is unclear to a newcomer. I will probably dig into the code to try to better understand.
For example the first two formulas:

```
(1) Cluster Idle Cost = ( Cluster Asset Costs -  Workload Costs )

(2) Cluster Idle % = ( Idle Cost / Resource Allocation Costs )
```

Is `Idle Cost` in (2) the same as `Cluster Idle Cost` in (1)? If so, they should have the same denomination.

Later in the section we have a loose definition of `Asset Idle Cost` and `Workload Idle Cost`.

So we have four concepts: `Cluster Idle Cost`, `Cluster Idle`, `Asset Idle Cost`, `Workload Idle Cost` and I personally struggle to understand their definitions, nuances and relationships.

Another unclear part (but maybe it's traced somewhere) if it's all of the above concepts are implemented in code or not.

Anyway, I am willing to help here if needed.

**Comment by nikovacevic** [comment]
Thanks for your comment @mfornasa, and for your eagerness to help! I'll try to add some clarification to these terms, as I understand them:

"Cluster Idle" and "Cluster Idle Cost" are the same, so there are really three concepts in play. They correspond to the forms of idle derivative of the following three costs:  cluster compute cost; workload allocated cost; workload used cost.

For example, if you have one node with one workload, and the workload has resource requests and some amount of usage, then you can compare the ratios of:
1. cost of CPU/RAM on the node
2. cost of CPU/RAM allocated to the workload
3. cost of CPU/RAM used by the workload (which might be less than what is allocated, due to requests)

Then, starting with those definitions:
* "Workload Idle Cost" is `(2) - (3)`
* "Cluster Idle Cost" is `(1) - (3)`
* "Asset Idle Cost" is `(1) - (2)`

(I am not as certain of the last two, and may have the names mixed up... but in any case, those are the types.)

**Comment by lmello** [comment]
Hi @nikovacevic , 

This is little bit old and dead discussion, but wanted to contribute some points to the discussion. 

 calling the (2) - (3) as workload idle cost might be confusing, I prefer your initial suggestion to call that as workload efficiency, because this translates on how much we are using of what we requested, and if we are requesting too much more than we are using we have an efficiency problem, monitoring this efficiency could mean improving the cost efficiency of the workload and saving money.
Also, this is not idle, because when k8s allocate this to the workload no other workload can use it.

The other two names are good. 

It is just that as an admin of a k8n cluster I would care only about (1) - (2) as idle. because this will be my lever to pull to scale up and down the cluster. The (1) -(3) does not matter for that reason, because of the way the kubernetes scheduler works, it reserves the requested CPU/Mem, so even if the application owner is not using it, from the point of view of the k8s administrator they are being used and not idle. 

so (2) - (3) will be used to give optimization insights to users of the k8s cluster, while (1) - (2) will give insights to the administrators of the k8s cluster. 

That is another reason that using the name workload efficiency for (2) - (3) is more appealing for the workload owners (users of the cluster)

**Comment by nikovacevic** [comment]
Thank you @lmello. I tend to agree with both your reasoning and conclusions here. That is, I agree that "workload efficiency" is a helpful idea, and that "idle cost" is best used as a description of the Kubernetes assets that aren't allocated to a pod's containers.

That said, I also think that the same basic ideas can be expressed fruitfully many different ways. One such way is to use the word "idle" for different ideas (as the spec does currently), and to do so in a clear fashion. As such, I would support either a clarification to the existing definitions, or a clarifying change to a different definition, as you suggest.

**Comment by mattray** [comment]
https://github.com/opencost/opencost/issues/1270 seems like undocumented behavior and that it's already there?
