### ISSUE TITLE
Cost Allocations aggregation by Teams is leaky

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#1412]
When aggregating by the Team label, pods and namespaces with the label applied are included, but Workloads in the namespace may not be included (DaemonSets, Deployments, StatefulSets). Pods that replace tagged pods don't get the labels (unless specified), so they can drop out as well. Users (customers) expect a team-labeled namespace to contain the Workloads in the namespace.

Potentially related to https://github.com/opencost/opencost/issues/1329

**Comment by AjayTripathy** [comment]
Maybe a flag to enable consumption/collection of workload labels? Most of our allocation model is based on pods today but I'm not opposed other than for reasons of cardinality.

**Comment by nabadger** [comment]
@mattray I think I am seeing something similar. 

When I query the allocations API ( (aggregating by `pod,container` and `accumulate=false`) sometimes see the same workload with and without pod labels. This makes aggregating by labels somewhat broken, since the costs for some of the pods can end up `__unallocated__`.

In my case, it seems like the pods affected are all  from statefulset workloads, so the pod name remains consistent. The pods in question have been running for around 24hrs, so plenty of time for prometheus to scrape them.

Can you confirm if you think this is still an issue?  Is there any information I can provide that would be helpful here? 

I'm particularly interested in 

> Pods that replace tagged pods don't get the labels (unless specified), so they can drop out as well

Is this something I can configure as a user (since it says _unless specified_), or any other workarounds?
