### ISSUE TITLE
Option to add additional Columns 

### ISSUE THREAD

**Issue by sppwf** [opencost/opencost#1416]
Hi Guys,

Is it possible to add additional Columns to the cost allocation csv file? The idea is that i would like to have an allocation report per deployment and add to csv file as well additional labels key/value for each object. Label key to be the Column name.

Thanks
Sergiu Plotniciu

**Comment by AjayTripathy** [comment]
Hey @sppwf this doesn't seem too hard. We can consider it for v1.99 -- @Adam-Stack-PM mind helping triage?

**Comment by Adam-Stack-PM** [comment]
+1 to build on the idea would propose we allow users to configure the export columns. For large users, these reports could be very large, and this could also reduce the processing time.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
