### ISSUE TITLE
Add documentation for running OpenCost as a Prometheus exporter

### ISSUE THREAD

**Issue by dwbrown2** [opencost/opencost#1575]
**Is your feature request related to a problem? Please describe.**
We had this before OpenCost creation: https://github.com/opencost/opencost/blob/da55364e680851c8c6315073c6413aa0aac8caec/kubecost-exporter.md
Was dropped here: https://github.com/opencost/opencost/pull/1369

**Describe the solution you'd like**
Proposal is we bring this documentation back (as opencost-exporter.md or opencost-prom-exporter.md) because it's important functionality!

**Comment by Pokom** [comment]
Would it be worthwhile to have this documentation live on the website as well?

**Comment by dwbrown2** [comment]
+1, that's probably the best source of truth IMO now that the project has a dedicated docs site!

**Comment by jessegoodier** [comment]
+1

question I have:
If opencost does not have a prometheus to scrape, the logs will have errors reflecting that.

I'm not seeing a method to disable querying prometheus?

Current idea:
1. move the exporter.md to opencost-website docs
2. create new opencost.yaml without the UI container (because there will be nothing to query)

@mattray / Webb,
Please let me know your thoughts on this. I will create branches with the above changes.

**Comment by jessegoodier** [comment]
https://github.com/opencost/opencost/pull/1578
and
https://github.com/opencost/opencost-website/pull/69

**Comment by mattray** [comment]
@jessegoodier I think this looks good. This will provide a useful setup for folks who only want the exporter.

**Comment by mattray** [comment]
Docs merged
