### ISSUE TITLE
Same name for pvc in different namespaces triggers query error

### ISSUE THREAD

**Issue by boniek83** [opencost/opencost#1768]
Opencost version:
kubecost1/kubecost-cost-model:latest as of today

Every five minutes I get something like this in logs:
` ERR CostDataRange: Request Error: Prometheus communication error: 422 (Unprocessable Entity) Headers: { Server: [ nginx/1.22.1 ], Date: [ Tue, 14 Mar 2023 16:39:03 GMT ], Content-Type: [ application/json ], Content-Length: [ 652 ], Connection: [ keep-alive ], Vary: [ Accept-Encoding ] }, Body: {"status":"error","errorType":"execution","error":"found duplicate series for the match group {namespace=\"monitoring\", persistentvolumeclaim=\"redis-data-polyaxon-redis-slave-1\"} on the left hand-side of the operation: [{namespace=\"monitoring\", persistentvolumeclaim=\"redis-data-polyaxon-redis-slave-1\", storageclass=\"nfs-client\", volumename=\"pvc-1e992c5b-e720-41be-b8f9-aeec7f301bce\"}, {namespace=\"monitoring\", persistentvolumeclaim=\"redis-data-polyaxon-redis-slave-1\", storageclass=\"nfs-client\", volumename=\"pvc-6d7ef2b8-f0ba-11e9-b28c-525400366508\"}];many-to-many matching not allowed: matching labels must be unique on one side"} Query: avg(avg(kube_persistentvolumeclaim_info{volumename != ""}) by (persistentvolumeclaim, storageclass, namespace, volumename, cluster_id, kubernetes_node)`
Context for PV seen in logs:
```
boniek@boniek-desktop:~> k get pv pvc-1e992c5b-e720-41be-b8f9-aeec7f301bce
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                               STORAGECLASS   REASON   AGE
pvc-1e992c5b-e720-41be-b8f9-aeec7f301bce   8Gi        RWO            Retain           Bound    polyaxon-test/redis-data-polyaxon-redis-slave-1   nfs-client              2y137d
boniek@boniek-desktop:~> k get pv pvc-6d7ef2b8-f0ba-11e9-b28c-525400366508
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                        STORAGECLASS   REASON   AGE
pvc-6d7ef2b8-f0ba-11e9-b28c-525400366508   8Gi        RWO            Retain           Bound    polyaxon/redis-data-polyaxon-redis-slave-1   nfs-client              3y149d
```
This is triggered by the same name for pvc in two different namespaces.
This fixes it (basically group_left instead of group_right):
```avg(avg(kube_persistentvolumeclaim_info{volumename != ""}) by (persistentvolumeclaim, storageclass, namespace, volumename, cluster_id, kubernetes_node) 	* on (persistentvolumeclaim, namespace, cluster_id, kubernetes_node) group_left()
	sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{}) by (persistentvolumeclaim, namespace, cluster_id, kubernetes_node, kubernetes_name)) by (persistentvolumeclaim, storageclass, namespace, cluster_id, volumename, kubernetes_node)

**Comment by AjayTripathy** [comment]
Thanks for the report @boniek83 
@kirbsauce can we get someone assigned to try and repro this? If so we should likely modify the query.

**Comment by kirbsauce** [comment]
Will do.

**Comment by rossfisherkc** [comment]
Taking a stab at this without repro, I can dig further tomorrow if needed when on shift;

Generally, if there are two Persistent Volume Claims (PVCs) with the same name but in different namespaces, it can trigger a query error in Prometheus if the query does not properly account for the different namespaces.

many-to-many matching not allowed: matching labels must be unique on one side occurs because the Prometheus query is unable to handle duplicate PVC names across different namespaces, leading to the "duplicate series for the match group" error.

Per the docs: https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching

"One-to-one matching means that each element in the left-hand side vector matches with exactly one element in the right-hand side vector and vice versa. If the match is not unique on both sides, the result is a many-to-many matching which is not allowed."

In the issue reported, the duplicate PVC names across different namespaces resulted in many-to-many matching, which is not allowed. To resolve this, we'd need to ensure that the matching labels are unique on one side. In this case, differentiating based on the namespace and other relevant labels is crucial

The documentation also provides information on group_left and group_right functions:

group_left: This function is used when you have a one-to-many relationship from the right-hand side vector to the left-hand side vector. It means that each element in the right-hand side vector can match with multiple elements in the left-hand side vector. When using group_left, you need to specify the labels that should be preserved from the left-hand side vector.

group_right: This function is used when you have a one-to-many relationship from the left-hand side vector to the right-hand side vector. It means that each element in the left-hand side vector can match with multiple elements in the right-hand side vector. When using group_right, you need to specify the labels that should be preserved from the right-hand side vector.

I think it's safe to say that updating our query would fix it. Question, is this an example query in the docs, or in the code somewhere?

**Comment by kirbsauce** [comment]
thanks @rossfisherkc ! My understanding is this is in the code.

**Comment by rossfisherkc** [comment]
Found it:
https://github.com/opencost/opencost/blob/d8516a70f951ec2aceb89747dba007d0da7cd315/pkg/costmodel/costmodel.go#L191

Could rewrite to:
```
queryPVRequestsStr = `avg(avg(kube_persistentvolumeclaim_info{volumename != ""}) by (persistentvolumeclaim, storageclass, namespace, volumename, %s, kubernetes_node)
	*
	on (persistentvolumeclaim, namespace, %s, kubernetes_node) group_left(storageclass, volumename)
	sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{}) by (persistentvolumeclaim, namespace, %s, kubernetes_node, kubernetes_name)) by (persistentvolumeclaim, storageclass, namespace, %s, volumename, kubernetes_node)`
```

By changing the query to use group_left, we ensure that the metrics are grouped based on the PVCs, namespace, and other labels, thus resolving the issue with duplicate series and ensuring proper matching between the two sets of time series (vectors).
https://github.com/rossfisherkc/opencost/compare/develop...rossfisherkc-patch-1

Pretty easy change, not sure if this breaks anything else or what tests would need to be modified

Sounds like I need to get an OC cluster setup

**Comment by AjayTripathy** [comment]
@rossfisherkc were we able to repro this? @cliffcolvin this should be tracked in JIRA if not already

**Comment by rossfisherkc** [comment]
Hey @AjayTripathy 

It's been long enough ago that I no longer have it around, may also need to re-verify on the latest version of Kubecost to verify it's still an issue

**Comment by billabongrob** [comment]
@rossfisherkc - I would say this is still a relevant error message - I am seeing a similar 

`CostDataRange: Request Error: Prometheus communication error: 422 (Unprocessable Entity) Headers: { Strict-Transport-Security: [ max-age=15724800; includeSubDomains ], Date: [ Mon, 25 Sep 2023 18:41:55 GMT ], Content-Type: [ application/json ], Connection: [ keep-alive ] }, Body: {"status":"error","errorType":"execution","error":"found duplicate series for the match group {namespace=\"REDACTED-062623-vcluster-1\", persistentvolumeclaim=\"REDACTED-vcluster-1-0\"} on the left hand-side of the operation: [{namespace=\"REDACTED-062623-vcluster-1\", persistentvolumeclaim=\"REDACTED-vcluster-1-0\", storageclass=\"gp2\", volumename=\"pvc-dbb9fd70-5900-4aba-a5ff-f7a733aa2156\"}, {namespace=\"REDACTED-062623-vcluster-1\", persistentvolumeclaim=\"REDACTED-vcluster-1-0\", storageclass=\"gp2\", volumename=\"pvc-cc355914-efb2-46c6-9b1e-dc4ffd0b9a4e\"}];many-to-many matching not allowed: matching labels must be unique on one side"}`

For what it's worth, when setting the env CLUSTER_ID I'm not seeing any values set for cluster_id raw data from the opencost exporter

on version
Image:          quay.io/kubecost1/kubecost-cost-model:latest                                                                                                                           
Image ID:       quay.io/kubecost1/kubecost-cost-model@sha256:731e25d49bafce51d12e08f8df7c0089dc4810fde0b66c001c40526d5c763056

Errors similar to this more recent issue:  #2176

**Comment by artydeez** [comment]
Was this issue ever resolved. I have the same issues happening in the latest opencost versions (ghcr.io/opencost/opencost:1.114.0). It still doesn't like when a PVC is named the same thing but in different namespaces

**Comment by wkd-woo** [comment]
+1
