### ISSUE TITLE
Incorrect OnDemandRateCodeCn configuration

### ISSUE THREAD

**Issue by aapelismith** [opencost/opencost#1777]
https://github.com/opencost/opencost/blob/3507d95d08803ef541ce3f147b40db500d10c1b6/pkg/cloud/awsprovider.go#L304

The current correct OnDemandRateCodeCn is 5Y9WH78GDR

![image](https://user-images.githubusercontent.com/44763019/225816008-d3f5c3ca-93be-412e-9a45-cff57942dddf.png)

**Comment by aapelismith** [comment]
`
curl -s https://pricing.cn-north-1.amazonaws.com.cn/offers/v1.0/cn/AmazonEC2/current/cn-northwest-1/index.json -O index.json

cat index.json | jq -r '.terms.OnDemand' | grep offerTermCode | awk -F '"' '{print $4}' | sort | uniq
`

**Comment by AjayTripathy** [comment]
I think this is just the ratecode for China pricing. Let's get this looked at as part of the fixes planned for v1.102

**Comment by AjayTripathy** [comment]
@ameijer is looking into this!

**Comment by ameijer** [comment]
@AjayTripathy , looks like this could be attributable to a difference in the way that the AWS API behaves (and consequently, how we handle the rate code) for the CN endpoint vs the US endpoint. Check this out: 

```
$ curl -s https://pricing.cn-north-1.amazonaws.com.cn/offers/v1.0/cn/AmazonEC2/current/cn-northwest-1/index.json | jq '.terms.OnDemand' | grep offerTermCode | sort | uniq
      "offerTermCode": "5Y9WH78GDR",
      "offerTermCode": "KW44MY7SZN",
$ curl -s https://pricing.cn-north-1.amazonaws.com.cn/offers/v1.0/cn/AmazonEC2/current/index.json | jq '.terms.OnDemand' | grep offerTermCode | sort | uniq
      "offerTermCode": "5Y9WH78GDR",
      "offerTermCode": "99YE2YK9UR",
      "offerTermCode": "KW44MY7SZN",
$ curl -s https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json | jq '.terms.OnDemand' | grep offerTermCode | sort | uniq
      "offerTermCode": "JRTCKXETXF",
$ curl -s https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-east-1/index.json | jq '.terms.OnDemand' | grep offerTermCode | sort | uniq
      "offerTermCode": "JRTCKXETXF",
```
So, it seems that everyone is correct, in a fashion. Our existing constant `99YE2YK9UR` is correct and is still a valid on demand rate code (if perhaps not used in cn-northwest-1), as are the rate codes from @aapelismith. This is in notable contrast to the behavior of the us-east-1 endpoint, which returns the same rate code for the region and multi region endpoints . 

Likely we will need to move to a set for these, rather than a string constant to cover the case of n > 1 rate codes for a given region.

**Comment by mattray** [comment]
This is addressed in https://github.com/opencost/opencost/pull/1803
