### ISSUE TITLE
Refactor `pkg/cloud` directory 

### ISSUE THREAD

**Issue by Pokom** [opencost/opencost#1788]
Looking to kick off a conversation about starting to split out
the CSP's into dedicated modules. The primary motivation is to support
calculating out of cluster costs. My proposal is that our cloud directoy
starts to look like the following: `pkg/cloud/${CSP}/${csp.go}`. Then we
can start placing external costs code in a dedicated file
(`${csp}_external.go` or specific folders.

One thing I discovered from this process is that there is a _lot_ of
coupling between csp's that make changing code hard. I discovered a number of
import cycles that existed. In order to decouple the CSP's and resolve
the import cycles, I started to split out shared code into three
directories:

- `models`
- `utils`
- `provider`

Models has shared definitions for structs and interfaces that don't
change csp to csp.
Utils has some shared utilities across all the cps's.
Provider has the `providerconfig` struct that is used across all of the
CSP's.

I recognize this is a _massive_ change based upon LoC, and so I suggest
we first evaluate whether or not this structure makes sense. If it does,
my proposal is to get a build available that I can roll out across the
three primary CSP's in Grafana's dev environment. This can help sus out
major issues early on.

**Comment by Pokom** [comment]
@Sean-Holcomb @AjayTripathy @mbolt35 @nikovacevic I wanted to get this in front of everyone for review(Ajay said everyone here is a stakeholder). I'm proposing we create a deeper directory level in the `cloud` folder so we can start adding external asset implementations per cloud provider. I've detailed some of the challenges I ran into simply moving providers to dedicated modules and wanted to get some thoughts on whether or not this is the right direction.

**Comment by Sean-Holcomb** [comment]
Hey Pokom, thanks for writing this up and the draft PR. We have been doing some refactoring on our end that is somewhat akin to this. There a few things to talk about with what you have said here. The first one is that while CSP division makes sense here because the way functionality is grouped in the provider interface, in our closed source we have some more modular interfaces which we have packaged separately (also under a `cloud` pkg). Having seen some of the work that you have done I am hoping that in the near term we can open-source some of our cloud configuration and integration which you could leverage or emulate the patterns of to continue our ongoing effort to make csp integration configuration more uniform across the application. In this world our file structure would look something like:
```
cloud
|--config
|--serviceintegrations
|--provider
```

The Provider interface itself and its implementations are also something of a point of contention right now. There current state is the result of them being a dumping ground for all features which relate to a specific CSP. As it stands there is a proposal out which at a high level suggests separating the functionality required for a cluster existing in a specific CSP and what is called a `PricingSource` into a more concise interface. Moving forward it would be best if functionality is not added to the providers, and that we find a better home for it (likely using the above file structure).

As for the External Assets, Kubecost as a product is currently moving away from the Cloud/External Assets idea. Moving forward we Assets will be specifically Kubernetes Assets. Cloud/External Assets are being replace with CloudCost which like a `Cloud` type asset is meant to be a general representation of a resource usage across all providers. With that being said it sounds like you want to do something with service specific implementations across providers. I would say that the benefit of doing this is that it gives a level of detail that the general representations cannot provide, as such trying to push these representations back into the Asset or CloudCost types, defeats the purpose. Given the lack of standardization between the CSP and even between services I would suggest that we come up with data model that gives the level of granularity that we want. As an example if these types were broken out only to the CSP level, you could specify the pricing model you wanted to use. For AWS that would be blended, unblended and amortized in addition to net versions of each. This is not something we can fully support in the Asset or CloudCost view, because in a multi-CSP environment we do not have access to all of these pricing models.

**Comment by AjayTripathy** [comment]
Hey @Sean-Holcomb this is a separate idea to hydrate Cloud / External Assets with additional data from Opencost and build out APIs/metrics to fetch that data for the additional detail; then Kubecost and other Opencost users can use that data to improve their pricing models and estimates.

**Comment by Sean-Holcomb** [comment]
@AjayTripathy I understand the need for additional detail here, my point is that Assets/CloudCost are not good places for additional detail. If we take S3 buckets as an example, we get information on them from the S3 api, so now we have every detail we want about the S3 bucket. If we push that into assets we can A) strip the details off of it to make it into an asset. B) Dilute the meaning of asset to include S3 details. I am not supportive of either. It would be more useful to have an S3 bucket type as part of an AWS view and/or CSP-agnostic bucket-storage view, both of which would be able to surface more relevant detail.

**Comment by Sean-Holcomb** [comment]
I am supportive of the S3 details and prediction idea as a whole, to be clear

**Comment by Pokom** [comment]
Sorry @Sean-Holcomb there's quite a bit of details in your comments to digest, and the changing of terminology is confusing for me to follow. So let me start by making clear my primary goal of _this_ PR is to address this point:

> The Provider interface itself and its implementations are also something of a point of contention right now. There current state is the result of them being a dumping ground for all features which relate to a specific CSP. 

My first stab at implementing S3 I wanted to avoid rewriting the pricing parser logic. This is when I realized how tightly coupled the providers were to each other and made me start to split them apart. 

> Having seen some of the work that you have done I am hoping that in the near term we can open-source some of our cloud configuration and integration which you could leverage or emulate the patterns of to continue our ongoing effort to make csp integration configuration more uniform across the application. 

Is this on your roadmap with someone actively working on? I'd love to take advantage of what's already been written, but would prefer not to put down my work unless it's going to be picked up in the next week or two. 

What you've said about not coupling the S3(`CloudCost`) to the Provider resonates and matches what I've already started to implement. I feel S3 should implement a separate interface so you can then have an implementation of S3(Object Storage) per provider. To me it would make no sense to add this to the existing asset provider. Stuffing the providers with every detail is a pattern in the codebase I'd love to see us move on from. 

So if we're all in agreement about where the S3 implementation should live _and_ that it's not part of _this_ PR, can I get a bit more feedback on the structural changes in the pr? I'd be more then happy to update it to reflect this directory structure:

```
cloud
|--config
|--serviceintegrations
|--provider
```

**Comment by Sean-Holcomb** [comment]
Here is a draft PR with the config and serviceintegrations https://github.com/opencost/opencost/pull/1823
If you would like to discuss in more detail and plans moving forward we can set up a call.

**Comment by Pokom** [comment]
Hey @Sean-Holcomb thanks for letting me know! I won't have an opportunity this week to look through in depth. I'll try to provide some very high level feedback before end of the week just so we can some things to talk about.

We do have two community meetings for OpenCost next week that we can discuss this. I think would be more beneficial for the overall community instead of 1:1, but I'm open to whatever you feel is easiest.

**Comment by mattray** [comment]
@Pokom @Sean-Holcomb Is this issue still valid? https://github.com/opencost/opencost/pull/1787 was closed but I didn't see another PR to replace it.

**Comment by Pokom** [comment]
@mattray this has been completed. #1869 and #1902 did a majority of the work.
