### ISSUE TITLE
Missing aws permissions

### ISSUE THREAD

**Issue by trondhindenes** [opencost/opencost#1809]
**Describe the bug**
In the logs, I see references to various AWS services, such as
`ERR Failed to lookup reserved instance data: no reservation data available in Athena`
and
`WRN Skipping AWS spot data download: operation error S3: ListObjects, https response error StatusCode: 403`

However, there's no mention of aws permissions or aws-specific setup in the documentation as far as I've found. It would be good if the docs provided some info regarding how to set up opencost in an aws environment, any cloud provider-specific considerations etc. I'm not asking for anything super-detailed, just enough to let the reader understand how it's supposed to work

**To Reproduce**
Install opencost via quickstart, inspect opencost container for error / warning output

**Expected behavior**
Just enough docs to let me understand how to setup opencost in our aws environment

**Screenshots**

**Which version of OpenCost are you using?**
latest

**Additional context**

**Comment by ashwaq06** [comment]
Regarding the specific errors you mentioned in your logs, the first error `Failed to lookup reserved instance data: no reservation data available in Athena` suggests that opencost was unable to find any reserved instance data in Athena. This could be due to a misconfiguration or lack of permissions to access the necessary Athena resources.

The second error `Skipping AWS spot data download: operation error S3: ListObjects, https response error StatusCode: 403` indicates that opencost was unable to list objects in an S3 bucket due to a permissions issue. Ensure that the IAM user or role being used by opencost has the necessary permissions to list objects in the S3 bucket.

 when setting up opencost in an AWS environment, ensure that you have the necessary permissions and setup for accessing AWS services, and make sure that the IAM user or role being used by opencost has the necessary permissions to access the required resources.

**Comment by KofiSQ** [comment]
The problem I think is  which bucket is this trying to list from

**Comment by ashwaq06** [comment]
t's possible that the issue is related to the permissions for the S3 bucket that opencost is trying to access. The error message mentions a "StatusCode: 403" response, which typically means that the user or role making the request doesn't have sufficient permissions to access the requested resource.

To resolve the issue, you may need to review the IAM policies attached to the AWS user or role that opencost is using to access S3. Make sure that the policies include the necessary permissions to list objects in the S3 bucket.

Another possible issue is that the S3 bucket name or region is not configured correctly in the opencost configuration. Double-check the configuration settings for the S3 bucket and make sure that they are accurate and up-to-date.

It may also be helpful to review the opencost documentation and any available resources related to running opencost in an AWS environment. This could provide additional guidance on any AWS-specific configuration requirements or best practices.

**Comment by bryanasdev000** [comment]
I think the main issue here is that we need to manually correlate documentation from both opencost and kubecost docs to properly set it up.

For example, kubecost provide vendor specific docs:

- https://docs.kubecost.com/install-and-configure/install/cloud-integration
- https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations

And opencost docs doesn't mention anything specific for vendors.

**Comment by mattray** [comment]
https://www.opencost.io/docs/configuration/aws#aws-spot-instance-data-feed-configuration should cover this
