### ISSUE TITLE
Unnecessary Multiplying container requests by the count of Prometheus samples

### ISSUE THREAD

**Issue by bboreham** [opencost/opencost#1965]
**Describe the bug**
This query is rather mysterious: https://github.com/opencost/opencost/blob/0195d83081a609ad4dccc0737129acc59ce3fe53/pkg/costmodel/costmodel.go#L147-L149

`count_over_time` reports how many samples are available to Prometheus.  Say you scrape every minute and the window is 1 hour, this will be 60 every time (barring failures).
`avg_over_time` is as the name suggests.  Most of the time, requests on a container never change, so this is just the request.

So, why multiply the request by the count?  Without knowledge of the scrape rate and how many failures happened in the time window, it seems to make the result meaningless.

Assuming I'm just failing to see why this is necessary, the expression simplifies to `sum_over_time`.

**Expected behavior**
Just ask for what you need.

**Additional context**
I'm not actually running OpenCost; I'm debugging an unrelated issue in a Prometheus service.
But this query really threw me.

**Comment by mattray** [comment]
@bboreham there doesn't seem to be any rationale for not optimizing the query. If you want to submit a PR fixing it, I'm sure we'd merge it assuming it doesn't have any performance downsides (which it shouldn't). Right @Pokom?

**Comment by bboreham** [comment]
Do you know what it is supposed to be computing?  Maybe I didn’t explain that very well, but I couldn’t figure out what anyone could use the number for.

**Comment by r2k1** [comment]
I believe the `avg_over_time * count_over_time` can be replaced with `sum_over_time` in this scenario.

Using `avg_over_time` alone would not be accurate when the pod is only available for part of the time, as it does not account for missing values. For instance, if you request data for a 24-hour period and the pod was running for 12 hours with 100MB request, averaging over time would yield 100MB. However, for cost allocation purposes, you would need 50MB.

To achieve the desired result, in other project I used the following Prometheus query:

```
sum_over_time(kube_pod_container_resource_requests[24h:1m]) / scalar(count_over_time(vector(0)[24h:1m]))
```

This will produce average over time treating missing data as zeros.

It's likely that instead of using `/ scalar(count_over_time(vector(0)[24h:1m]))`, opencost applies some post-calculation in its code.

**Comment by mattray** [comment]
I believe this was fixed here: https://github.com/opencost/opencost/commit/f7ae181d03c93fcc5a3aa6d0a33048b3ee154788

**Comment by bboreham** [comment]
I see #2297 has further discussion on why this computation is done.
