### ISSUE TITLE
Feature Request: Add metrics for max CPU and RAM usage and requests

### ISSUE THREAD

**Issue by mehulpurohit97** [opencost/opencost#2019]
Hello OpenCost team,

I'm currently using OpenCost for monitoring Kubernetes resource allocation and I find it extremely useful. However, there are some additional metrics that I believe would enhance the capabilities of OpenCost and provide users with a more comprehensive understanding of their resource usage.

The metrics I'd like to request are:

- max cpuCoreRequest
- max cpuCoreUsage
- max ramByteRequest
- max ramByteUsage

The inclusion of these metrics would allow users to better understand their peak resource usage and requests, enabling more efficient resource allocation within their Kubernetes clusters.

I kindly request you to consider these features for a future update of OpenCost. I believe that these additional metrics would not only benefit me, but they would also be helpful for other users as well.

Thank you for your time and for your efforts on this project.

Best regards,
Mehul Purohit

**Comment by mattray** [comment]
@AjayTripathy, @Pokom and @r2k1 what do you think?

**Comment by r2k1** [comment]
How you would like to present this information? Adding extra prometheus metrics may not be necessary since querying them is already straightforward. 

I would like to see this information in the UI. I think it's valuable for adjusting pod requests (and potential cost reduction).

Maybe in slightly different format:
- avg cpuCoreRequest
- max cpuCoreUsage
- avg cpuCoreUsage
- avg ramByteRequest
- max ramByteUsage
- avg ramByteUsage

**Comment by mattray** [comment]
I think I see the value of this being in the API, I think this is worth leaving open as an enhancement
