### ISSUE TITLE
use hostname as kubernetes node name  cpu & ram cost is not correct

### ISSUE THREAD

**Issue by little-guy-lxr** [opencost/opencost#2270]
**Describe the bug**
use hostname as kubernetes node name , the cost of the cpu /ram is calculated by the request value not usage
**To Reproduce**

Use hostname ad kubernetes node name

**Expected behavior**

the cost of the cpu/ram shoule be is calculated by the usage value

**Comment by mattray** [comment]
Thanks for opening an issue. To clarify a bit, are you saying you expect to see the output of `hostname` instead of something else? I'm not seeing this in my own deployments but if you could explain what you're looking for and what you're seeing that may help us address the issue. 

And the cost of the CPU and RAM are determined by the maximum of the request and usage, so the request will always be the floor.
