### ISSUE TITLE
OpenCost UI doesn't report version/build number

### ISSUE THREAD

**Issue by mattray** [opencost/opencost#2323]
**Describe the bug**
When the costmodel container starts up it reports 
```
2023-11-21T20:19:37.749036463Z INF Starting cost-model version dev (HEAD)
```
where `HEAD` is the actual SHA when not building from source. This is super useful for rebuildling older releases if they weren't tagged properly.

**Comment by brito-rafa** [comment]
I've looked into it.

I could not find the github action that is pushing the opencost container as
`quay.io/kubecost1/kubecost-cost-model:latest`
which is the image we have on the kubernetes deployment example to install opencost.

This container is indeed showing the version + commit information:


```
% docker run quay.io/kubecost1/kubecost-cost-model:latest

(...)
2023-12-03T13:32:31.350705291Z INF Starting cost-model version 1.107.1 (cdb18e6)

```

I found three different ways to build opencost on the github repo: A) `Makefile`; B) `Dockerfile`; C) `justfile`. Not sure which one is considered official, perhaps "C" because there is reference of it on contributing file.


*Option A*,  nothing needed to be done on `Makefile`. It sets version by the script `./tool/image-tag`:

```
% make
CGO_ENABLED=0 go build -ldflags "-extldflags \"-static\" -s -w -X github.com/opencost/opencost/pkg/version.Version=2323-build-version-952357de-WIP -X github.com/opencost/opencost/pkg/version.GitCommit=952357de" ./cmd/costmodel

% ./cmd/costmodel/costmodel
2023-12-03T06:33:56.500831-06:00 INF Starting cost-model version 2323-build-version-952357de-WIP (952357de)
```

*Option B*, using existing `Dockerfile` - it needs to be called with the correct environment variables.


Without env variables (note the lack of version info)

```
% docker build . -t opencost:rafatest

% docker run opencost:rafatest

(...)
2023-12-03T12:43:00.153015047Z INF Starting cost-model version dev (HEAD)
```

With correct build variables

```

% docker build \
--build-arg "version=$(./tools/image-tag)" \
--build-arg "commit=$(git rev-parse --short HEAD)" \
--no-cache . -t opencost:rafatest

% docker run opencost:rafatest

(...)
2023-12-03T13:40:33.50758101Z INF Starting cost-model version 2323-build-version-952357de-WIP (952357de)

```


*Option 3*, using `just`, in this case, I found it has the `version` variable hard-coded to `dev` https://github.com/opencost/opencost/blob/develop/justfile#L3 and the image was not getting the correct version:

```
% just build quay.io/brito_rafa0/opencost:justtest

% docker run quay.io/brito_rafa0/opencost:justtest
Unable to find image 'quay.io/brito_rafa0/opencost:justtest' locally
justtest: Pulling from brito_rafa0/opencost
Digest: sha256:26039809ecd3cd5834f1f699a482fa9fab3f211fada07bbbdbb1d555bf3f9e73
Status: Downloaded newer image for quay.io/brito_rafa0/opencost:justtest

(...)2023-12-03T13:58:08.663894429Z INF Starting cost-model version dev (952357de)
```

After I tweaked the `justfile` to use the same approach as the `Makefile`, I was able to get the version. FWIW, I am putting the PR to change it (along with a tweak on the contributing file.)

**Comment by brito-rafa** [comment]
I volunteer to document what action is generating `quay.io/kubecost1/kubecost-cost-model:latest` and perhaps deprecates one (or two) of the three ways we are using to build images.

**Comment by mattray** [comment]
I merged #2359, but the cost-model opencost container isn't the issue, it's getting something similar in the opencost-ui log (or even bettter, real tiny on the UI itself for reporting purposes).

**Comment by brito-rafa** [comment]
This issue is related to #2368  since we need to determine how the image is being built.

**Comment by brito-rafa** [comment]
I added the info on the opencost-ui log for now. See https://github.com/opencost/opencost/pull/2388 . Not sure how to label this "next release".
