### ISSUE TITLE
Deploy only 1 opencost if we have a centralized prometheus

### ISSUE THREAD

**Issue by afreyermuth98** [opencost/opencost#2673]
Hello, I have a multi env architecture where for example my envA, envB and envC are sending metrics to remote prometheus inside envM using OTel. So it's the prometheus inside envM that have all the metrics.
Is is possible deploy only 1 opencost on this envM to get all the metrics about the cost of my environment ? 
On what I understand, it seems that we need to deploy one opencost on each cluster / env we have. Tell me if I'm wrong !

**Comment by mattray** [comment]
OpenCost currently does not support multiple clusters, you must install 1 Prometheus and 1 OpenCost per cluster. However, you can forward your metrics to a centralized Prometheus-compatible database (Thanos, Cortex, Mimir, VictoriaMetrics, etc.), but it's not documented yet. Anecdotally several folks have gotten this working and I've been told the UI even supports running against the centralized DB.

https://github.com/opencost/opencost-website/issues/194 has been opened to address this, but we haven't had anyone step up and document the process. I'm closing this issue since we have an outstanding documentation bug for it.
