### ISSUE TITLE
Append AWS NAT Gateway processing charges if configured

### ISSUE THREAD

**Issue by shaikatz** [opencost/opencost#522]
Hi guys,

In AWS if you have NAT Gateway in your VPC, each GB going to the internet from your pods will be billed an extra $0.045.
I would like to see a feature that lets me define a setting that says: `I'm using NAT Gateway for my cluster, please add $0.045/GB to my internet egress cost`.

Thanks
Shai

**Comment by dwbrown2** [comment]
@shaikatz thanks for reporting! This is part of the reason why we made internet egress rate configurable [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/ab384e2eb027e74b2c3e61a7e1733ffa1718170e/cost-analyzer/values.yaml#L434).

Definitely think there could an opportunity for doing more here in the future. Just curious, how are you using NAT gateways at a high-level today? Are most of your resources accessing the internet with them?

**Comment by shaikatz** [comment]
hi @dwbrown2.
That's a great idea adding that there, my initial thought was that the egress costs are set automatically by the cost data fetched from the provider.
But if we anyway need to define it manually, adding that $0.045 is possible :-)

Regards your question, the NAT Gateway is our path out from the VPC, meaning, every egress traffic goes through it.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
