### ISSUE TITLE
Support hashicorp vault aws auth

### ISSUE THREAD

**Issue by Valiev** [opencost/opencost#612]
It would be convenient if `kubecost` supports vault aws auth machinery (https://www.vaultproject.io/docs/auth/aws). In that case not secrets (`service-key.json`) needed to assume IAM Role with permissions for access Cost Usage Report.

**Comment by AjayTripathy** [comment]
Hi @Valiev we can look into this. I'm a little unclear on what's required here-- do any of the auth solutions we support here: https://github.com/kubecost/docs/blob/master/aws-cloud-integrations.md look like they can be made to work with vault?

**Comment by Valiev** [comment]
Hi @AjayTripathy! The main idea is the following: 
1. you have k8s and vault integration, so containers could authorise in vault easily 
2. also, there is vault and aws integration, so vault provide you access (allow to assume certain roles) to AWS resources

In that setup you no longer need to create AWS User and store it's key in secrets.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
