### ISSUE TITLE
Cluster sizing recommendations do not consider AKS spot instances

### ISSUE THREAD

**Issue by munjalpatel** [opencost/opencost#700]
Hello,

My AKS cluster is a mix of Azure spot and non-spot instances.

Currently Sizing recommender does not realizes that a node is a `Spot` instance and hence gives inaccurate recommendations. Also, the recommended `B-Series` is not available for `Spot`

<img width="409" alt="image" src="https://user-images.githubusercontent.com/2717686/108751910-af328580-74f7-11eb-9855-df6e9b2596f6.png">

**Comment by dwbrown2** [comment]
@munjalpatel today, this feature does not consider usageType, e.g. spot vs on-demand. It provides a recommendation on the amount of resources required.

**Comment by munjalpatel** [comment]
Any plans to enhance this feature to properly understand instance type?

**Comment by dwbrown2** [comment]
This is actually being built separately but will likely be integrated in the future! No set timeline at this point.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
