### ISSUE TITLE
Allow filter by cluster on "Local disks with low utilization" saving page

### ISSUE THREAD

**Issue by kbrwn** [opencost/opencost#808]
Multicluster/Federated customers would like to be able to filter by cluster on this page as in some clusters low disk utilization is not a concern.

**Comment by dwbrown2** [comment]
Strong +1, there's a couple structural changes that we will want to make here. This will bring this API to be more consistent with our other savings APIs. Let us plan to review in an upcoming sprint session!

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
