### ISSUE TITLE
Show difference between RIs/Savings Plans pricing and public API pricing in Allocation Pipeline 

### ISSUE THREAD

**Issue by AjayTripathy** [opencost/opencost#824]
Use cases:

* Custom analysis: Certain organizations can't bill their dev teams based on savings plans because the dev teams don't have control over making reservations/buying savings plans.

* Clearly show the effectiveness of savings plans/RIs for users using savings plans.

Implementation ideas:
* Create a flag that stops using savings plan data to estimate costs, then create an adjustment column to break out savings/RI discounts in the Allocation API.

gz#364

**Comment by dwbrown2** [comment]
Would it be more appropriate to support a blended cost measurement? In most cases, I've seen someone should received from RIs.

**Comment by AjayTripathy** [comment]
I think we can generalize to support different pricing breakdown styles but I think if we're starting somewhere public pricing + adjustment to amortized makes sense.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
