### ISSUE TITLE
Consider eks default CNI pod per node limits by class when recommending instance sizes

### ISSUE THREAD

**Issue by AjayTripathy** [opencost/opencost#844]
The EKS default CNI has per-node pod limits that deviate significantly from the 110 pods-per-node limit most k8s CNIs support (https://kubernetes.io/docs/setup/best-practices/cluster-large/). Our current recommendation for cost-conscious teams is to migrate away from the default CNI (https://medium.com/@swazza85/dealing-with-pod-density-limitations-on-eks-worker-nodes-137a12c8b218), but we should make this recommendation clear on cluster-sizing.html or try to take this into account.

Here's a list of the EKS default CNI limitations
https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt

gz#471

**Comment by dwbrown2** [comment]
+1, I actually think there are several other constraints we can review when adding new features to cluster right-sizing

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
