### ISSUE TITLE
Suspicious spot prices calculation for AWS when no spot data feed enabled

### ISSUE THREAD

**Issue by teqwve** [opencost/opencost#882]
Hi,

after deploying kubecost on AWS cluster without changing default prices, or configuring spot feed I got suspiciously low CPU and RAM prices on spot nodes.
<details>
<summary>A fragment of response from `/model/costDataModel'.</summary>
<p>

```
(...)
"node": {
  "hourlyCost": "0.1720000000",
  "CPU": "4",
  "CPUHourlyCost": "0.034190",
  "RAM": "8 GiB",
  "RAMBytes": "8256716800.000000",
  "RAMGBHourlyCost": "0.004583",
  "storage": "EBS only",
  "storageHourlyCost": "",
  "usesDefaultPrice": false,
  "baseCPUPrice": "0.031611",
  "baseRAMPrice": "0.004237",
  "baseGPUPrice": "0.95",
  "usageType": "ondemand",
  "gpu": "",
  "gpuName": "",
  "gpuCost": "",
  "instanceType": "c5a.xlarge",
  "region": "eu-west-1",
  "providerID": "...",
}
(...)
"node": {
  "hourlyCost": "",
  "CPU": "8",
  "CPUHourlyCost": "0.000661",
  "RAM": "16 GiB",
  "RAMBytes": "16623628288.000000",
  "RAMGBHourlyCost": "0.000089",
  "storage": "1 x 300 NVMe SSD",
  "storageHourlyCost": "",
  "usesDefaultPrice": false,
  "baseCPUPrice": "0.031611",
  "baseRAMPrice": "0.004237",
  "baseGPUPrice": "0.95",
  "usageType": "preemptible",
  "gpu": "",
  "gpuName": "",
  "gpuCost": "",
  "instanceType": "c5ad.xlarge",
  "region": "eu-west-1",
  "providerID": "...",
}

```

</p>
</details>

As you can see calculated price for on-demand instance is `0.034190 * 4 + 0.004583 * 8 = 0.173424` and matches numbers from AWS price list. But calculated price for spot instance is `0.000661 * 8 + 0.000089 * 16 = 0.006712` which is quite strange, as spots aren't ~50 times cheaper ;) Values from this response are the same as recorded in `node_ram_hourly_cost` and `node_cpu_hourly_cost` metrics (this is why I initially started to looking at this).

After looking into the code I found that:

1. In my case (spot instance without spot feed configured) price for the node is set in second if in `createNode` ([here](https://github.com/kubecost/cost-model/blob/b1bca3e90e94e751afaec9b25d3e19989b6aae59/pkg/cloud/awsprovider.go#L1039)), total cost is not set, ram cost is not set and cpu cost is set to value of `spotCPU` field from config

1. Later, in costmodel, it's handled by second if of `GetNodeCost` (`else if newCnode.RAMCost == "" {` [here](https://github.com/kubecost/cost-model/blob/9b039e80ae040e16479eb59fa9e8a76b77f34298/pkg/costmodel/costmodel.go#L1118)), executed code (cleared from error handling and some branches) looks like this:

   ```
   ram = ...
   cpu = ...

   defaultCPU, err := strconv.ParseFloat(cfg.CPU, 64)
   defaultRAM, err := strconv.ParseFloat(cfg.RAM, 64)

   cpuToRAMRatio := defaultCPU / defaultRAM

   ramGB := ram / 1024 / 1024 / 1024

   ramMultiple := cpu*cpuToRAMRatio + ramGB

   # Because node total cost was not set by the provider, here we go into the second branch and the following line is executed:
   nodePrice, err = strconv.ParseFloat(newCnode.VCPUCost, 64) // all the price was allocated the the CPU

   ramPrice := (nodePrice / ramMultiple)
   cpuPrice := ramPrice * cpuToRAMRatio
   ```

So this two steps combined mean that calculated prices equal:

```
ramPrice = nodePrice / ramMultiple  = config.spotCPU / (node.cpuCores * config.cpu / config.ram + cpu.ramGBs)
cpuPrice = ramPrice * cpuToRAMRatio = config.spotCPU / (node.cpuCores * config.cpu / config.ram + cpu.ramGBs) * config.cpu / config.ram
```

which is a little suspicious itself (values that depend on instance size are only in denominator, so increasing instance by two times times results in CPU and RAM prices lower by more than two times).

And if I calculate those expressions for default price config and instance size from my case (8 CPUs, 16 GBs of RAM) I got RAM price `0.006655 / (8 * 0.031611 / 0.004237 + 16) = 0.00008793` which is almost equal to what I saw in the respons.

The same goes with some m4.10xlarge spot instance. In metrics I can check that a value of `node_ram_hourly_cost` for some spot instance is `0.000015` (I didn't save any response from the api for this node) which matches value from this expression `0.006655 / (40 * 0.031611 / 0.004237 + 160 = 0.000015`. 

After enabling spot feed the issue disappears, prices look as expected.

So I'd like to ask if I the algorithm works as intended. My idea is that `nodePrice` is incorrectly calculated - CPU cost from cloud provider should be multiplied by number of cores:

```go
var nodePrice float64
if newCnode.Cost != "" {
	nodePrice, err = strconv.ParseFloat(newCnode.Cost, 64)
	if err != nil {
		klog.V(3).Infof("Could not parse total node price")
		return nil, err
	}
} else {
	nodePrice, err = strconv.ParseFloat(newCnode.VCPUCost, 64) // all the price was allocated the the CPU
	if err != nil {
		klog.V(3).Infof("Could not parse node vcpu price")
		return nil, err
	}
	nodePrice = nodePrice * cpu // line that's missing
}
```

Thanks in advance! And sorry if I missed something, I looked at the code quite briefly.

gz#632

**Comment by AjayTripathy** [comment]
Hi @teqwve thank you for the detailed report. We'll look into this-- to clarify, it sounds like spot pricing is WAI intended when the spot data feed is applied but our configured estimates until that data is available are not taking into account the number of CPU on a node?

**Comment by teqwve** [comment]
Yes, I think it's a good description - in this case node price is estimated using spot CPU price from the configuration, but number of cores isn't taken into account, so node price (and thus final CPU / RAM cost) seems to be way too low.

**Comment by AjayTripathy** [comment]
Looking into this soon-- assigned to @nealormsbee !

**Comment by nealormsbee** [comment]
Hi folks 👋 
I spent a chunk of time on this yesterday; here's a status update and some questions. I'm not all too familiar with this part of our codebase; careful scrutiny is appreciated.

The proposed solution of multiplying `nodePrice` by `cpu` to get `cpu` in the numerator does help with the directional accuracy of the pricing in this case (more nodes no longer gets cheaper). However, I think we may be facing some deeper issues.

For one, we'll still have exactly the same problem with RAM. There's no RAM in the numerator now, and I would expect higher-RAM nodes to appear cheaper than lower-RAM nodes. I don't think we want to just multiply `nodePrice` by `cpu` and `ram` -- that might help directionally / heuristically, but may not be very accurate.

### First problem
I think one issue comes from the noted section
```golang
if newCnode.Cost != "" {
	nodePrice, err = strconv.ParseFloat(newCnode.Cost, 64)
	if err != nil {
		klog.V(3).Infof("Could not parse total node price")
		return nil, err
	}
} else {
	nodePrice, err = strconv.ParseFloat(newCnode.VCPUCost, 64) // all the price was allocated the the CPU
	if err != nil {
		klog.V(3).Infof("Could not parse node vcpu price")
		return nil, err
	}
}
```

If we have no value for `newCNode.Cost` (`$/hr`), then we set `nodePrice = newCNode.VCPUCost` (`$/(cpu*hr)`). I imagine that there are cases where `VCPUCost` actually _does_ reflect the entire cost of the node, or this case wouldn't exist to begin with. This isn't one of those cases, though.

### Second problem
Something that's confusing me is the way that we distribute cost over CPU and RAM. Borrowing from @teqwve's example:
```golang
ramPrice = nodePrice / (cpu * cpuToRAMRatio + ramGB)
cpuPrice = ramPrice * cpuToRAMRatio = nodePrice * cpuToRAMRatio / (cpu*cpuToRAMRatio + ramGB)
```

So, if we try to add `ramPrice` and `cpuPrice` back together to get `nodePrice`, we get
```golang
nodePrice = ramPrice + cpuPrice
= nodePrice / (node.cpu * cpuToRAMRatio + node.ramGB) + nodePrice * cpuToRAMRatio / (node.cpu * cpuToRAMRatio + node.ramGB)
= (nodePrice * (1 + cpuToRAMRatio)) / (node.cpu * cpuToRAMRatio + node.ramGB)
= nodePrice / ((node.ramGB + node.cpu * cpuToRAMRatio) / (1 + cpuToRAMRatio))
```
so unless `(node.ramGB + node.cpu * cpuToRAMRatio) / (1 + cpuToRAMRatio) == 1`, I don't think we get back to `nodePrice` with this sum. That holds when `node.cpu == node.ramGB == 1`, but I don't think it holds for other case.

### Possible solution 1
One idea is to add a field to the returned node in `awsprovider`:
```golang
 else if aws.isPreemptible(key) { // Preemptible but we don't have any data in the pricing report.
	log.DedupedWarningf(5, "Node %s marked preemptible but we have no data in spot feed", k.ID())
	return &Node{
		VCPU:         terms.VCpu,
		VCPUCost:     aws.BaseSpotCPUPrice,
		RAM:          terms.Memory,
		RAMCost:      aws.BaseSpotRAMPrice,  // this is the new field
		GPU:          terms.GPU,
		Storage:      terms.Storage,
		BaseCPUPrice: aws.BaseCPUPrice,
		BaseRAMPrice: aws.BaseRAMPrice,
		BaseGPUPrice: aws.BaseGPUPrice,
		UsageType:    PreemptibleType,
	}, nil
}
```
The presence of this field would cause us to bypass the `else if newCnode.RAMCost == "" {` block of `costmodel` entirely. It looks like [this exact field was removed some time ago](https://github.com/kubecost/cost-model/pull/630). I don't know why yet, but putting it back may send us down a path of playing bug-whack-a-mole.

### Possible solution 2
Another idea is to add a different field to the node returned by `awsprovider`. Specifically, `Cost`.
Having `Cost` available on the node in `costmodel` would allow us to use that instead of `VCPUCost`, which seems to solve at least part of the problem -- CPU and RAM would now be represented in the numerator. Issues with this idea are that `Second problem` remains a problem, and more importantly that we would have to do a bunch of `strconv.ParseFloat()` in `awsprovider`, combine the `cpu`, `ram`, `cpuCost`, and `ramCost`, and then convert the result back into a string. That's doable, but it feels like the string parsing and math is meant to be done in `costmodel`.

### Possible solution 3
The last idea is to treat `node.VCPUCost` as the CPU cost, rather than as the total cost of the node, and use the `cpuToRAMRatio` to work our way towards a RAM cost and a total cost. This might work well. As noted in `First Problem`, though, there may be cases where `VCPUCost` actually _does_ reflect the entire cost of the node, and such a change would break those cases.

That's where I'm at so far -- thoughts, corrections, and guidance all much appreciated. I can look into the viability of the possible solutions listed above. It seems possible that none of them will work especially well, but we can cross that bridge if we come to it.

**Comment by paalkr** [comment]
Even after enabling the spot feed this bug is annoying, because it can take a few hours before the spot feed bucket is updated with data about a particular instance. So the first few hours a node runs, the price will be totally wrong. This is especially problematic when using Cluster Auto Scaler. A workload, say some data processing, running for a few hours on a fresh node will get a to low cost.

![image](https://user-images.githubusercontent.com/9726307/140046959-50472733-13c1-4fad-954d-534ad070aaaf.png)

**Comment by AjayTripathy** [comment]
Hi @paalkr , understood. We support [tuning our estimates ](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L640) via our configs to reduce the difference. What else would you like to see here?

**Comment by kbrwn** [comment]
@paalkr Do you have any further comments on this issue?

**Comment by evgenii-denisov** [comment]
I have the same issue.
Typical spot nodes cost for m4.2xlarge around $0.210 per/h
But kubecost use $0.007 per/h
Spot feed enabled, and i'm download a csv file from feed and found exactly one of problematic instance.
This file in s3 available  at least for 2 hour after data for this specific instance is appeared.
Instance created at 01:15:15 UTC and s3 file uploaded at 06:06:42 UTC (5 hour lag)
But even after spot data become available kubecost do not change the price.

![Screenshot 2022-03-20 at 10 21 06](https://user-images.githubusercontent.com/100626206/159152491-63bb0781-8c62-46bb-9687-2112bed1ee19.png)

It is very annoying, and make Kubecost completely useless.

**Comment by AjayTripathy** [comment]
Hi @evgenii-denisov can you look at /diagnostics.html and let us know if you've correctly connected to the spot feed? An error log would be helpful as well.

**Comment by evgenii-denisov** [comment]
![Screenshot 2022-03-21 at 14 47 49](https://user-images.githubusercontent.com/100626206/159255187-33730a51-29ee-4f0c-bf66-9fabaa9814e7.png)

@AjayTripathy  I can't find any error in `cost-model` container, just a lots of following warnings:
```
...
I0321 11:47:06.581453       1 log.go:32] [Warning] Asset ETL: node 'ip-172-22-168-210.eu-west-1.compute.internal' end outside window: 2022-03-21T11:01:00 not in [2022-03-21T10:00:00, 2022-03-21T11:00:00]
I0321 11:47:06.581461       1 log.go:32] [Warning] Asset ETL: node 'ip-172-22-169-183.eu-west-1.compute.internal' end outside window: 2022-03-21T11:01:00 not in [2022-03-21T10:00:00, 2022-03-21T11:00:00]
...
I0321 11:47:06.582772       1 log.go:32] [Warning] Asset ETL: disk 'ip-172-22-173-90.eu-west-1.compute.internal' end outside window: 2022-03-21T11:01:00 not in [2022-03-21T10:00:00, 2022-03-21T11:00:00]
I0321 11:47:06.582778       1 log.go:32] [Warning] Asset ETL: disk 'ip-172-22-171-163.eu-west-1.compute.internal' end outside window: 2022-03-21T11:01:00 not in [2022-03-21T10:00:00, 2022-03-21T11:00:00]
...
I0321 11:51:41.067191       1 log.go:32] [Warning] CPU cost outlier detected; skipping data point.
I0321 11:51:41.067197       1 log.go:32] [Warning] RAM cost outlier detected; skipping data point.
```
and few
```

I0321 10:22:49.934196       1 log.go:32] [Warning] SummaryAllocation: failed to compute attached volume costs: missing asset resource totals for node prod-m/
I0321 10:23:09.755846       1 log.go:32] [Warning] SummaryAllocation: detected invalid sharing coefficient for prod-m/ip-172-22-168-73.eu-west-1.compute.internal/default/service-6db6b9954d-n4cj9/service: 0
...
I0321 10:23:54.413741       1 log.go:32] [Warning] Compute Idle Allocations: Node Cost Adjusted to $0.00 for ip-172-22-169-120.eu-west-1.compute.internal
```

**Comment by evgenii-denisov** [comment]
Connecting to `spot feed` seems does not matter, as sometimes feed data for node comes to s3 already then node removed from cluster after 5-6 hours. We should somehow recalculate cost after getting real numbers from AWS.

Or may be at least fallback to previous average values as source of cost for spot instance for the same type of nodes.

**Comment by AjayTripathy** [comment]
Hi @evgenii-denisov we do support backdating prices-- but they do not backdate in Prometheus or via the spot feed. Changes are reflected in our UI, not prometheus, by connecting to the AWS CUR : https://guide.kubecost.com/hc/en-us/articles/4407595928087-AWS-Cloud-Integration#step-1-setting-up-the-cur

**Comment by KKatsnel** [comment]
Hi,
I’ve faced this issue in Opencost, and it looks critical to me because there is no possibility of enabling spot feed in Opencost. We widely use spot instances in AWS, so without correct prices for spot instances, Opencost is useless for us.
Should I create a separate issue for Opencost (because this issue has a “Kubecost” label)?

**Comment by mattray** [comment]
@KKatsnel yes, a separate OpenCost-specific issue would be more useful.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
