### ISSUE TITLE
Support a label/tag that can be used to prevent cost allocation for a resource or cloud asset.

### ISSUE THREAD

**Issue by kbrwn** [opencost/opencost#945]
Kubecost should support a label/tag that can be used to prevent cost allocation for a resource or asset. This would provide flexibility in situations where regular cost allocation may not suit the end-user needs.

**Comment by dwbrown2** [comment]
Thanks for reporting, Kyle! Can you think of a recent example where you'd use this? Would this almost be like a permanent filter applied to all reports? If so, would our RBAC filter options be pointed in the right direction?

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
