### ISSUE TITLE
Estimate costs based on user-provided request sizes

### ISSUE THREAD

**Issue by kirbsauce** [opencost/opencost#968]
It would be beneficial to have a feature whereby one could enter in CPU, RAM, and possibly a profile (Production, Dev, etc), and combine with historic usage and cloud provider pricing to estimate cost.

Currently, we try to seek out something similar in our installation, but it's often difficult to find something similar and likely not as close as what might be estimated by Kubecost.

**Comment by dwbrown2** [comment]
If we have historic usage on a workload, then we can already have an opinion on what it should cost as part of right-sizing. Is that that helpful? Let me know if there's more!

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
