### ISSUE TITLE
Expand size and configuration recommendations to HPA

### ISSUE THREAD

**Issue by kirbsauce** [opencost/opencost#975]
While one might be able to extrapolate the necessary HPA adjustments from the individual pod recommendations and metrics, it would be more straightforward to simply recommend, for example, the minimum number of pods.

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
