### ISSUE TITLE
Restrict sizing recommendations to supported instance types

### ISSUE THREAD

**Issue by kirbsauce** [opencost/opencost#985]
We are recommending resizing to a1 instance types in AWS, however A1 instance types aren't available in some regions a cluster is operating in. AWS has the nasty habit of rolling out new instance types to only a handful of regions. Can we ensure an instance type is available in the region we are recommending a change in?

@srpomeroy @kbrwn @michaelmdresser 
#gz967

**Comment by michaelmdresser** [comment]
For clarity: this is a request to fix feature incompleteness of cluster right-sizing.

Current cluster right-sizing recommendations are based on a snapshot of available instances in a single region. We need to update this to either have a snapshot of all regions (easier) or live-load data for relevant regions (harder, but more robust long-term if implemented correctly).

**Comment by michaelmdresser** [comment]
@AjayTripathy I'd like to get this prioritized, even if we want to do something really small to make this less confusing for users. Your thoughts?

**Comment by mattray** [comment]
This issue is being closed because it may not be relevant to the OpenCost project and appears stale. If you feel this was closed in error, please open a [new OpenCost issue](https://github.com/opencost/opencost/issues) with updated details or if it is still relevant for Kubecost please open an issue with [Kubecost Support](https://support.kubecost.com).
